# Generated by Django 2.2.24 on 2022-03-16 11:10

import account.models
import account.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=25, unique=True, validators=[account.validators.validate_email])),
                ('is_active', models.BooleanField(default=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id_candidate', models.CharField(default=account.models.increment_candidate, max_length=3, primary_key=True, serialize=False)),
                ('nama_depan', models.CharField(max_length=25, null=True)),
                ('nama_belakang', models.CharField(max_length=25, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('perempuan', 'Perempuan'), ('laki-laki', 'Laki-laki')], default='laki-laki', max_length=25)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto_profil', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('cv', models.FileField(blank=True, default='cv.pdf', upload_to='')),
                ('status', models.CharField(choices=[('seleksi', 'Seleksi'), ('ditolak', 'Ditolak'), ('diterima', 'Diterima')], default='seleksi', max_length=25)),
                ('cand_mail', models.OneToOneField(blank=True, limit_choices_to={'is_leader': False, 'is_staff': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
