# Generated by Django 2.2.24 on 2022-03-16 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lowongan',
            fields=[
                ('id_lowongan', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mata_pelajaran', models.CharField(choices=[('ipa', 'IPA'), ('ips', 'IPS'), ('b.indonesia', 'B.Indonesia'), ('matematika', 'Matematika'), ('b.inggris', 'B.Inggris')], default='matematika', max_length=25)),
                ('jenjang', models.CharField(choices=[('sma', 'SMA'), ('sd', 'SD'), ('smp', 'SMP'), ('tk', 'TK')], default='sd', max_length=10)),
                ('status', models.CharField(choices=[('dibuka', 'Dibuka'), ('ditutup', 'Ditutup')], default='ditutup', max_length=10)),
                ('tgl_buka', models.DateField(default=django.utils.timezone.now, null=True)),
                ('tgl_tutup', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
