# Generated by Django 2.2.24 on 2022-03-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('kriteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nilai',
            fields=[
                ('id_nilai', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nilai', models.FloatField(null=True)),
                ('nama_alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.candidate')),
                ('nama_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kriteria.kriteria')),
            ],
        ),
    ]
