# Generated by Django 2.2.24 on 2022-03-16 11:10

from django.db import migrations, models
import kriteria.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kriteria',
            fields=[
                ('id_kriteria', models.CharField(default=kriteria.models.increment_kriteria, max_length=3, primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(max_length=25, null=True)),
                ('kaidah', models.CharField(choices=[('minimasi', 'Minimasi'), ('maksimasi', 'Maksimasi')], max_length=10, null=True)),
                ('tipe_preferensi', models.CharField(choices=[('quasi', 'II: Quasi'), ('level', 'IV: Level'), ('linear', 'III: Linear'), ('usual', 'I: Usual'), ('linear-quasi', 'V: Linear-Quasi')], max_length=25, null=True)),
                ('parameter_p', models.FloatField(default=0, null=True)),
                ('parameter_q', models.FloatField(default=0, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
