# Generated by Django 2.2.24 on 2022-03-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify',
            fields=[
                ('id_verify', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('verifikasi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='peringkat',
            fields=[
                ('id_peringkat', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nilai_akhir', models.FloatField(null=True)),
                ('urutan', models.IntegerField(null=True)),
                ('nama_lengkap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.candidate')),
            ],
        ),
    ]
